Feature/use statement
mun-lang/mun pull request #290
Opened 2020-12-29 23:37 UTC by baszalmstra

Adds the use of `use` statements in the code. 

#### ✔️ Features

- [x] Parsing of use statements (e.g. `use foo::bar::{Bar, Baz}`)
- [x] Resolve all use statements in all modules

#### ❓ Missing features, but planned

- [ ] Errors for cyclic use statements
- [ ] Errors for unresolved use statement
- [ ] Wildcard use statements
- [ ] Errors for illegal import statement visibility 
- [ ] Errors for leaking non-visibile types

#### ❌ Out of scope

- Runtime dependencies (so this is actually not actually usable yet)

2021-02-15 02:08 UTC, Wodann requested changes
Nicely done. No comments about the architecture or code; just a couple of requests in terms of spelling, grammar, and documentation.

2021-02-15 02:08 UTC, Wodann commented on crates/mun_hir/src/visibility.rs
> +    /// Returns true if an item with this visibility is accessible from the module from the
```suggestion
    /// Returns true if an item with this visibility is accessible from the module of the
```

2021-02-15 02:08 UTC, Wodann commented on crates/mun_syntax/src/parsing/grammar/declarations.rs
> +                // if we are parsing a nested tree, we have to eat a token to main balanced `{}`
```suggestion
                // if we are parsing a nested tree, we have to eat a token to remain balanced `{}`
```

2021-02-15 02:08 UTC, Wodann commented on crates/mun_syntax/src/parsing/grammar/declarations.rs
> +                // if we are parsing a nested tree, we have to eat a token to main balanced `{}`
?

2021-02-26 14:24 UTC, baszalmstra commented on crates/mun_hir/src/code_model/module.rs
> +        module_tree[parent]
The parent has a mapping from name to child.

2021-02-27 17:21 UTC, Wodann approved these changes

2021-02-28 12:40 UTC, merged