feat(language server): removed async code and switched to lsp_server
mun-lang/mun pull request #295
Opened 2021-01-11 22:22 UTC by baszalmstra

Depends on #294 

This PR removes all async code and switch to the use of the `lsp_server` crate instead of using our own.

2021-01-12 17:57 UTC, baszalmstra commented
I also added some basic functionalities for testing the language server properly. This now also fixes the shortcomings in #293 where the language server was slower than the tests. With the new vfs we can now wait until the entire workspace is loaded before requesting information about it.

2021-01-16 19:40 UTC, Wodann requested changes
Looks good overall. Some minor change requests.

2021-01-16 19:40 UTC, Wodann commented on crates/mun_language_server/src/state/protocol.rs
> +    /// Sends a response to a request to the client. This method logs the time it took us to reply
```suggestion
    /// Sends a response to the client. This method logs the time it took us to reply
```

2021-01-16 19:40 UTC, Wodann commented on crates/mun_language_server/src/state/protocol/dispatcher.rs
> +    /// Wraps-up the dispatcher. If the the request was not handled, report back that this is an
```suggestion
    /// Wraps-up the dispatcher. If the request was not handled, report back that this is an
```

2021-01-16 19:40 UTC, Wodann commented on crates/mun_language_server/tests/support.rs
> +use std::fs;
Merge `use` statements

2021-01-16 19:40 UTC, Wodann commented on crates/mun_language_server/tests/support.rs
> +/// A `Project` represents a project that a language server can work with. Call the `server` method
By adding `[..]` to the server, it should become a link to the actual server in docs

2021-01-16 19:40 UTC, Wodann commented on crates/mun_language_server/tests/support.rs
> +    /// Construct a project from a fixture.
```suggestion
    /// Constructs a project from a fixture.
```

2021-01-16 19:40 UTC, Wodann commented on crates/mun_language_server/tests/support.rs
> +    /// Instantiate a language server for this project.
```suggestion
    /// Instantiates a language server for this project.
```

2021-01-16 21:24 UTC, Wodann requested changes

2021-01-16 21:24 UTC, Wodann commented on crates/mun_language_server/src/analysis.rs
> +    pub fn request_cancellation(&mut self) {
```suggestion
    pub fn request_cancelation(&mut self) {
```

2021-01-16 23:03 UTC, Wodann approved these changes

2021-01-16 23:03 UTC, merged