feat: add mut keyword
mun-lang/mun pull request #305
Opened 2021-01-28 16:17 UTC by mkhan45

Adds the `mut` keyword and updates a lot of tests to accomodate for it. 

Closes #199.

:tada:

2021-01-28 18:31 UTC, baszalmstra requested changes
Thanks for this great PR! I've added some cosmetic comments but other than that it looks good to me!

2021-01-28 18:31 UTC, baszalmstra commented on crates/mun_codegen/src/ir/body.rs
> +                Pat::Bind { name, mode: _ } => {
I think using `..` is a bit nicer here.
```suggestion
                Pat::Bind { name, .. } => {
```

2021-01-28 18:31 UTC, baszalmstra commented on crates/mun_codegen/src/ir/body.rs
> +            Pat::Bind { name, mode: _ } => {
Same here
```suggestion
            Pat::Bind { name, .. } => {
```

2021-01-28 18:31 UTC, baszalmstra commented on crates/mun_hir/src/diagnostics.rs
> +pub struct ImmutableLHS {
Maybe something like `ReassignmentToImmutableBinding` or something?

2021-01-28 18:31 UTC, baszalmstra commented on crates/mun_hir/src/ty/infer.rs
> +                        if !self.check_mut_bind(&resolver, *lhs) {
I think it makes sense to turn this into an `else if` so that when you have something like `3=5` you don't get two errors.

2021-01-28 18:31 UTC, baszalmstra commented on crates/mun_hir/src/ty/infer/mut_bind.rs
> +            Expr::Field { expr, name: _ } => self.check_mut_bind(resolver, *expr),
```suggestion
            Expr::Field { expr, .. } => self.check_mut_bind(resolver, *expr),
```

2021-01-28 18:31 UTC, baszalmstra commented on crates/mun_syntax/src/parsing/grammar/patterns.rs
> +    }
```suggestion
    p.eat(T![mut]);
```

2021-01-28 18:31 UTC, baszalmstra commented on crates/mun_syntax/src/tests/parser.rs
> +    fn foo(mut a) {
Missing type after `a`

2021-01-29 08:33 UTC, baszalmstra approved these changes

2021-05-28 13:50 UTC, closed without merging

2021-05-29 00:11 UTC, mkhan45 commented
I didn't mean to close this; I think I updated the wrong branch on my side. I'll fix it tomorrow.