refactor: moved ApplicationTy into Ty
mun-lang/mun pull request #332
Opened 2021-06-27 19:51 UTC by baszalmstra

While working on arrays I encountered this recurring pattern of having to extract values fro the `ApplyTy` which seemed not necesarry. This is a refactor to simplify the use of `hir::Ty`. Previously a `Ty` was an enum that consisted of `Unknown`, `Apply`, `...`. This PR merges this into a single `TyKind`. `Ty` is now an `Arc<TyKind>` which should enable better sharing of types through the code. 

This PR also removes the `Empty` type and introduces the `Tuple` type. Besides a bit of support in the `TyKind` its not really supported throughout the rest of the code. The tests changed because `nothing` is now represented as `()`.

2021-07-10 22:05 UTC, Wodann requested changes

2021-07-11 10:37 UTC, baszalmstra commented on crates/mun_codegen/src/ir/ty.rs
> +        match return_type.interned() {
No, I did it this way because `return_type` is used below on line 146.

2021-07-11 10:38 UTC, baszalmstra commented on crates/mun_codegen/src/ir/ty.rs
> +        let return_type = ty.ret();
Same as above :)

2021-07-11 15:22 UTC, Wodann approved these changes
Nice refactor, makes it a lot simpler.

I'm just wondering for the parts of this code that aren't being tested yet, how could we add tests - in the future - to make it better? 🤔

2021-07-12 21:14 UTC, merged